# Task 3 - Dashboard analitico

Notebook da task 3 baseado nos Parquets e no contrato de dados produzidos pela task 2.

In [1]:
from pathlib import Path
import sys

sys.path.append(str((Path.cwd().parent / 'scripts').resolve()))

from common import load_environment, require_env
from analytics_dashboard import (
    build_dashboard,
    build_session,
    query_detailed_sales,
    query_dim_products,
    query_sales_by_country,
)

load_environment()
GLUE_DATABASE = require_env('GLUE_DATABASE')
session = build_session()
GLUE_DATABASE

'classicmodels_analytics'

In [2]:
dim_products_df = query_dim_products(GLUE_DATABASE, session)
dim_products_df.head(20)

,product_id,product_name,product_line,product_vendor
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,Min Lin Diecast
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,Classic Metal Creations
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,Highway 66 Mini Classics
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,Red Start Diecast
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,Motor City Art Classics
5,S10_4962,1962 LanciaA Delta 16V,Classic Cars,Second Gear Diecast
6,S12_1099,1968 Ford Mustang,Classic Cars,Autoart Studio Design
7,S12_4675,1969 Dodge Charger,Classic Cars,Welly Diecast Productions
8,S18_1097,1940 Ford Pickup Truck,Trucks and Buses,Studio M Art Models
9,S18_1129,1993 Mazda RX-7,Classic Cars,Highway 66 Mini Classics
10,S18_1342,1937 Lincoln Berline,Vintage Cars,Motor City Art Classics
11,S18_1367,1936 Mercedes-Benz 500K Special Roadster,Vintage Cars,Studio M Art Models
12,S12_1108,2001 Ferrari Enzo,Classic Cars,Second Gear Diecast
13,S12_1666,1958 Setra Bus,Trucks and Buses,Welly Diecast Productions
14,S12_2823,2002 Suzuki XREO,Motorcycles,Unimax Art Galleries
15,S12_3148,1969 Corvair Monza,Classic Cars,Welly Diecast Productions
16,S12_3380,1968 Dodge Charger,Classic Cars,Welly Diecast Productions
17,S12_3891,1969 Ford Falcon,Classic Cars,Second Gear Diecast
18,S12_3990,1970 Plymouth Hemi Cuda,Classic Cars,Studio M Art Models
19,S12_4473,1957 Chevy Pickup,Trucks and Buses,Exoto Designs

In [3]:
sales_by_country_df = query_sales_by_country(GLUE_DATABASE, session)
sales_by_country_df

       country total_sales
0          USA  3273280.05
1        Spain  1099389.09
2       France  1007374.02
3    Australia   562582.59
4  New Zealand   476847.01
5           UK   436947.44
6        Italy   360616.81
7      Finland   295149.35
8       Norway   270846.30
9    Singapore   263997.78

In [4]:
detailed_sales_df = query_detailed_sales(GLUE_DATABASE, session)
detailed_sales_df.head()

   full_date  product_line                  product_name country  total_sales
0 2004-11-02        Planes       1900s Vintage Tri-Plane     USA      2434.25
1 2003-10-28        Planes   American Airlines: B767-300     USA      2557.52
2 2003-10-28  Vintage Cars  1930 Buick Marquette Phaeton     USA      1906.08
3 2003-10-28        Planes                P-51-D Mustang     USA      1578.99
4 2003-07-24  Classic Cars               1982 Camaro Z28     USA      3641.40

In [ ]:
dashboard = build_dashboard(detailed_sales_df)
dashboard

VBox(children=(HBox(children=(DatePicker(value=datetime.date(2003, 1, 6), description='Inicio', step=1), DateP…